<a href="https://colab.research.google.com/github/yonghyunk1m/coding-notes/blob/master/PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Pytorch에 대해서 알아보도록 하자!**


> *참고자료: wikidocs.net/60034*



[Tensor]

Scalar (0D)
Vector (1D)
Matrix (2D)

In [4]:
import numpy as np

tensor_np_1D = np.array([0., 1., 2., 3., 4., 5., 6., 7.])
print(tensor_np_1D)
print("Rank: ", tensor_np_1D.ndim) # ndim: dimension number
print("Shape: ", tensor_np_1D.shape) # shape: size (or shape)

[0. 1. 2. 3. 4. 5. 6. 7.]
Rank:  1
Shape:  (8,)


In [5]:
tensor_np_2D = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(tensor_np_2D)
print("Rank: ", tensor_np_2D.ndim) # ndim: dimension number
print("Shape: ", tensor_np_2D.shape) # shape: size (or shape)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]
Rank:  2
Shape:  (4, 3)


In [6]:
import torch
tensor_pt_1D = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6., 7.])
print(tensor_pt_1D)
print("Dimension: ", tensor_pt_1D.dim)
print("Shape: ", tensor_pt_1D.shape)
print("Size(): ", tensor_pt_1D.size())

tensor([0., 1., 2., 3., 4., 5., 6., 7.])
Dimension:  <built-in method dim of Tensor object at 0x7fac106f9830>
Shape:  torch.Size([8])
Size():  torch.Size([8])


In [7]:
#Indexing, Slicing
print(tensor_pt_1D[0])
print(tensor_pt_1D[2:5])
print(tensor_pt_1D[2:])

tensor(0.)
tensor([2., 3., 4.])
tensor([2., 3., 4., 5., 6., 7.])


In [8]:
tensor_pt_2D = torch.FloatTensor([[1.,2.,3.],
                                  [4.,5.,6.],
                                  [7.,8.,9.],
                                  [10.,11.,12.]])

In [9]:
print(tensor_pt_2D.dim())
print(tensor_pt_2D.shape)
print(tensor_pt_2D.size())

2
torch.Size([4, 3])
torch.Size([4, 3])


Broadcasting

In [16]:
m1 = torch.FloatTensor([[3,3]]) #1*2
m2 = torch.FloatTensor([[5,5]]) #1*2
m3 = torch.FloatTensor([[2,3],[4,5]]) #2*2
print(m1+m2)
print(m1+m3)
print(m2*m3)
print(m3*m2)
print(m3.mul(m2))
m2_reshape = m2.reshape(2,1)
print(m3.matmul(m2_reshape))
print(m2.matmul(m3))

tensor([[8., 8.]])
tensor([[5., 6.],
        [7., 8.]])
tensor([[10., 15.],
        [20., 25.]])
tensor([[10., 15.],
        [20., 25.]])
tensor([[10., 15.],
        [20., 25.]])
tensor([[25.],
        [45.]])
tensor([[30., 40.]])


Mean, Sum

In [17]:
t = torch.FloatTensor([[1, 2], 
                       [3, 4]])
print(t.mean()) #2.5000
print(t.mean(dim=0)) #0(가로)성분 삭제 [2., 3.]
print(t.mean(dim=1)) #1(세로)성분 삭제 [[1.5], [3.5]] -> [1.5, 3.5]

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])


In [18]:
print(t.sum(dim=0))
print(t.sum(dim=1))

tensor([4., 6.])
tensor([3., 7.])


Max, Argmax

In [22]:
print(t.max())
print(t.max(dim=0))
print(t.max(dim=1))
print("Max (dim=0):",t.max(dim=0)[0])
print("Argmax (dim=0):",t.max(dim=0)[1])

tensor(4.)
torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
Max (dim=0): tensor([3., 4.])
Argmax (dim=0): tensor([1, 1])


[View]

원소의 수는 유지, 텐서의 Shape을 변경;

numpy에서의 reshape와 동일

In [23]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)
print(ft.size())

torch.Size([2, 2, 3])


In [26]:
# -1은 사용자가 모르겠으니 Pytorch보고 알아서 계산하라는 뜻
print(ft.view([-1,3]))
print(ft.view([-1,3]).size())
# view는 Shape 변경 전과 후에서 원소의 개수가 유지시키는게 가능해야함.

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [28]:
print(ft.view([1,-1,3]))
print(ft.view([-1,1,3]))

tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.],
         [ 6.,  7.,  8.],
         [ 9., 10., 11.]]])
tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])


Squeeze, Unsqueeze

Squeeze: 1인 차원을 제거
Unsqueeze: 특정 위치에 1인 차원을 추가

In [30]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.size()) # 3*1
print(ft.squeeze()) # 3; [0, 1, 2]
print(ft.squeeze().size())

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])
tensor([0., 1., 2.])
torch.Size([3])


In [32]:
ft = torch.Tensor([0, 1, 2]) # 3,
print(ft.shape)
print(ft.unsqueeze(0)) # 1*3으로 강제 변형: [[0, 1, 2]]
print(ft.unsqueeze(0).size())
print(ft.unsqueeze(1)) # 3*1으로 강제 변형: [[0],[1],[2]]
print(ft.unsqueeze(1).size())

torch.Size([3])
tensor([[0., 1., 2.]])
torch.Size([1, 3])
tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


Type Casting

32-bit floating point: *torch.float32 == torch.float* **torch.FloatTensor**

64-bit floating point: *torch.float64 == torch.double* **torch.DoubleTensor**

16-bit floating point: *torch.float16 == torch.half* **torch.HalfTensor**

8-bit integer (unsigned): *torch.uint8* **torch.ByteTensor**

8-bit integer (signed): *torch.int8* **torch.CharTensor**

16-bit integer: *torch.int16 or torch.short* **torch.ShortTensor**

32-bit integer: *torch.int32 or torch.int* **torch.IntTensor**

64-bit integer: *torch.int64 or torch.long* **torch.LongTensor**

In [34]:
lt = torch.LongTensor([1,2,3,4])
print(lt)
print(lt.float())

bt = torch.ByteTensor([True, False, False, True])
print(bt)
print(bt.long())
print(bt.float())

tensor([1, 2, 3, 4])
tensor([1., 2., 3., 4.])
tensor([1, 0, 0, 1], dtype=torch.uint8)
tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


Concatenating, Stacking

In [35]:
x = torch.FloatTensor([[1.,2.],[3.,4.]])
y = torch.FloatTensor([[5.,6.],[7.,8.]])
print(torch.cat([x,y], dim=0)) # 여기서 dim은 어디로 "늘릴까"를 의미한다. (예외적)
print(torch.cat([x,y], dim=1))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


In [42]:
x = torch.FloatTensor([1,2]) #2,
y = torch.FloatTensor([3,4]) #2,
z = torch.FloatTensor([5,6]) #2,

print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0))
print(torch.stack([x,y,z]))
print(torch.stack([x,y,z], dim=0))
print(torch.stack([x,y,z], dim=1))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[1., 3., 5.],
        [2., 4., 6.]])


In [46]:
x = torch.FloatTensor([[1.,2.],[3.,4.]])
y = torch.FloatTensor([[5.,6.],[7.,8.]])
print(torch.cat([x,y], dim=0)) # 2*2 2개 => 4*2
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0)], dim=0)) # 2*2 2개 => 2*2*2
print(torch.stack([x,y])) # 2*2 2개 => 2*2*2

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])
tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])


ones_like, zeors_like

모양은 같지만 채워지는 원소가 0 또는 1로만 구성

In [49]:
x = torch.FloatTensor([[0,1,2], [3,4,5]]) # 2*3
print(x)
print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[0., 1., 2.],
        [3., 4., 5.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In-place Operation

곱셈연산 뒤에 _(under score)를 붙이면 기존의 값을 덮어쓴다.

In [50]:
x = torch.FloatTensor([[1., 2.], [3., 4.]])

print(x.mul(2.))
print(x)

print(x.mul_(2.))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])


Python Class

In [53]:
# 함수로 덧셈기 구현하기
result = 0
def add(num):
  global result #기존 전역변수를 가져다 사용
  result += num
  return result

print(add(3))
print(add(4))

3
7


In [55]:
# 함수로 두개의 덧셈기 구현하기
result1 = 0
result2 = 0

def add1(num):
  global result1
  result1 += num
  return result1

def add2(num):
  global result2
  result2 += num
  return result2

print(add1(3))
print(add1(4))
print(add2(3))
print(add2(7))

3
7
3
10


In [57]:
#클래스로 편안하게 다수의 계산기 구현하기
class Calculator:
  def __init__(self):
    self.result = 0

  def add(self, num):
    self.result += num
    return self.result
  
  def sub(self, num):
    self.result -= num
    return self.result

c1 = Calculator()
c2 = Calculator()

print(c1.add(3))
print(c1.add(4))

print(c2.add(3))
print(c2.add(7))

3
7
3
10
